development:
  address: "smtp.gmail.com"
  port: 587
  domain: "gmail.com"
  authentication: "plain"
  user_name: "ntub.final@gmail.com"
  password: "AbCd123456"
  enable_starttls_auto: true
production:
  address: "smtp.gmail.com"
  port: 587
  domain: "gmail.com"
  authentication: "plain"
  user_name: "ntub.final@gmail.com"
  password: "AbCd123456"
  enable_starttls_auto: true
